environments_table = {
    "cartpole":                {"full": "CartPole-v1",              "args": None},
    "lander":                  {"full": "LunarLander-v3",           "args": {'gravity': -10.0}},
    "lander_continuous":       {"full": "LunarLander-v3",           "args": {'gravity': -10.0, 'continuous': True}},
    "cheetah":                 {"full": "HalfCheetah-v5",           "args": {'ctrl_cost_weight': 0.1}},
    "humanoid":                {"full": "Humanoid-v5",              "args": None},
    "ant":                     {"full": "Ant-v5",                   "args": None},
    "walker":                  {"full": "Walker2d-v5",              "args": None},
    "bipedal":                 {"full": "BipedalWalker-v3",         "args": {'hardcore': False}},
    "bipedal_hardcore":        {"full": "BipedalWalker-v3",         "args": {'hardcore': True}},
    "acrobot":                 {"full": "Acrobot-v1",               "args": None},
    "reacher":                 {"full": "Reacher-v5",               "args": {'reward_dist_weight': 5.}},
    "mountaincar_continuous":  {"full": "MountainCarContinuous-v0", "args": None},
    "mountaincar":             {"full": "MountainCar-v0",           "args": None},
    "pendulum":                {"full": "Pendulum-v1",              "args": {'g': 9.81}},
    "pusher":                  {"full": "Pusher-v5",                "args": None},
    "hopper":                  {"full": "Hopper-v5",                "args": None},
    "humanoid_standup":        {"full": "HumanoidStandup-v5",       "args": None},
    "inverted_d_pendulum":     {"full": "InvertedDoublePendulum-v5","args": None},
    "inverted_pendulum":       {"full": "InvertedPendulum-v5",      "args": None},
    "swimmer":                 {"full": "Swimmer-v5",               "args": None},
    "customcartpole":          {"full": "CustomCartpole",           "args": None}
}
